config/proc-aarch64.make
src/Mm/IntelOptimization.cc
src/Mm/IntelOptimization.hh

Added a ARM64 proc file and removed `-DDISABLE_SIMD` and `-DENABLE_SSE2` in favor of the predefined by the compiler `__SSE__` and `__SSE2__` .

Arm support and SSE check update

---

src/Nn/PythonControl.cc

I had a Bug when working with Python 3.8 that it a callback call in RETURNN, e.g. `callback("version")` would result in the error `"PythonControl callback(): unknown command 'v'"`, because only the first letter would be extracted from the first argument.
After some search I found this statement in the [Python-C documentation](https://docs.python.org/3.8/c-api/unicode.html?highlight=unicode_as_data#c.PyUnicode_AS_DATA) for the (actually deprecated) `PyUnicode_AS_DATA`
**It may also contain embedded null code points, which would cause the string to be truncated when used in most C functions** 
So I replaced this by the (hopefully correct) `PyUnicode_1BYTE_DATA` call including a check.

Fix char conversion in PythonControl callback

---

Makefile
src/Makefile

Otherwise compilation will crash with `Modules.hh` not found, as it does not exist yet when building parallel.

generate Modules.hh before starting parallel build

---

src/Lm/Module.cc
src/Lm/SimpleHistoryLm.hh

baseLM for next-step simple TF NLM
- A simple language model for token history extension and hashing
- also useful for no-LM recognition but still with recombination capability  or  just separate recombineLM usage

simple history LM

---

singularity/rasr.def
singularity/tensorflow.def
src/Lm/QuantizedCompressedVectorFactory.cc

1. TF 1.15.4 dependencies no longer available (-> upgrade to 1.15.5)
2. Add missing header include for AVX capable hosts
I noticed this when I build the singularity image to test another PR for compilation.

Fix 2 build issues

---

src/Bliss/CorpusDescription.cc
src/Bliss/CorpusDescription.hh
src/Bliss/CorpusParser.cc
src/Bliss/CorpusParser.hh

This is a draft PR for code that allows to remove the top-level/super corpus name from the segment full-name. 
This can be used to merge bliss files using the subcorpora mode while at the same time just merging feature and alignment bundle files without the necessity to rename all entries and create new files.
I am open to better naming suggestions of the parameter.
~~I am also not sure if I can hijack the "anonymous" default value like that, but this seemed to be the easiest approach so far.~~

Add remove-corpus-name-prefix parameter

---

src/Cart/DecisionTree.cc
src/Cart/DecisionTree.hh
src/Cart/Example.cc

backported from AppTek codebase

Fix encoding issues when writing CART examples/trees

---

src/Am/ClassicTransducerBuilder.cc
src/Am/ClassicTransducerBuilder.hh
src/Am/TransitionModel.cc
src/Am/TransitionModel.hh

Given a static allophone Finite State Acceptor (FSA), the `ClassicTransducerBuilder`, applies the transition penalties on the arcs. The Fsa at this level makes use of Epsilon arcs in order to distinguish between different word ends, including silence. In the current implementation, any arc coming after Epsilon arc will have speech forward penalty. This means that after trimming the Epsilon arcs, the transition penalty for leaving silence and final speech state is always the respective exit penalties plus speech forward. This should be corrected in the `doExit()` function in order to subtract the speech forward and add the silence forward, when leaving silence.

Allophone State Fsa bug for arc's weight leaving silence 

---

src/Lm/TFRecurrentLanguageModel.cc

This can happen when the user does not compile the tensorflow graph properly. Currently the code just segfaults without a warning.

Add an additional check to TFRecurrentLM to error if no states are detected

---

src/Am/TransitionModel.cc

With the refactoring in #14 the `Applicator` class was introduced in `Am/TransitionModel.cc`. In the `Am::TransitionModel::apply` function, a `std::unique_ptr<Applicator> ap` is created and set with either a `new LegacyApplicator` or `new CorrectedApplicator` afterwards, depending on the configuration.
However, `Applicator` did not have a virtual destructor, so since `ap` is an `Applicator` pointer, only the `Applicator` destructor is called after the function even though the actual object pointed to by `ap` is of type `LegacyApplicator` or `CorrectedApplicator`. This leads to a memory leak. See [here](https://wiki.sei.cmu.edu/confluence/display/cplusplus/OOP52-CPP.+Do+not+delete+a+polymorphic+object+without+a+virtual+destructor).
This PR fixes that memory leak by simply adding a virtual …

Fix TransitionModel Applicator memory leak

---

src/Tools/Analog/analog_util/parser.py

`gzip` [by default opens files in binary mode](https://docs.python.org/3/library/gzip.html#gzip.open)[^1], which is why the parser then breaks when processing the extracted data:
```
❯ wer --verbose-errors /long/path/redacted/for/brevity/search.log.1.gz
/u/mgunz/tools/rasr_no_tf/src/Tools/Analog/analog:14: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
import glob, imp, os, sys
Can not load PyQt. Gui will not work.
failed to load plug-in "ov": No module named 'sequitur_'
|                   word errors                    |  time 
file/subcorpus                | seg    del    ins    sub    errors words    wer  |  rtf …
```

Fix analog tool on .gz files

---

Modules.make
src/Tools/Lm/LmUtilityTool.cc
src/Tools/Lm/Makefile

Enable LM util tool again and remove some legacy imports so that it compiles again with the current version. Addresses issue #62.

Enable back LM util

---

src/Am/ClassicTransducerBuilder.cc
src/Am/ClassicTransducerBuilder.hh

For context-independent allophones (i.e. history_length = future_length = 0) the word-end states were not connected to the initial state in the `ClassicTransducerBuilder` which results in a broken automaton and a crash during training with `fast_bw` loss (e. g. CTC).
A fix for this behaviour had already been implemented in the original `label_sync_decoding` branch of @ZhouW321 but was missed when porting to github RASR. This PR re-applies the original fix.

Connect word ends to initial state for context-independent allophones

---

src/Flf/Traceback.cc

When performing recognition, the traceback contains word boundaries in the form of integers that represent output time frames of the model in the case of time-synchronous decoding. These word boundaries are then written into the lattice.
Later, when dumping the lattice to a .ctm file, these boundaries are divided by 100 to form start- and end-times as well as durations of words. This assumes that a frame shift on the output time axis is 1/100 seconds (i.e. 10ms) which is wrong when subsampling is performed in the model (or if one was to use feature extraction with a different frame shift). This leads to wrong word boundaries in the .ctm file.
This PR replaces the `/ 100.0` by a multiplication with a configurable frame shift.

Fix word boundaries in ctm dumps of lattices with subsampling

---

src/Bliss/SyntacticTokenMap.hh
src/Lm/AbstractNNLanguageModel.cc
src/Lm/AbstractNNLanguageModel.hh
src/Lm/ArpaLm.cc
src/Lm/BackingOff.cc
src/Lm/BackingOff.hh
src/Lm/BackingOffInternal.hh
src/Lm/CheatingSegmentLm.cc
src/Lm/CheatingSegmentLm.hh
src/Lm/FsaLm.cc
src/Lm/FsaLm.hh
src/Lm/LanguageModel.cc
src/Lm/LanguageModel.hh
src/Lm/NNHistoryManager.hh
src/Lm/ReverseArpaLm.cc
src/Lm/ReverseArpaLm.hh
src/Lm/ScaledLanguageModel.hh
src/Lm/check.cc
src/Search/AdvancedTreeSearch/LanguageModelLookahead.cc
src/Search/AdvancedTreeSearch/LanguageModelLookahead.hh
src/Search/AdvancedTreeSearch/SearchSpace.cc

Originally I wanted to only backport some fixes I made to the cheating LM, s.t. you can also do search-error experiments, but this escalated to many more changes in the LM codebase + some search related stuff. I tested that everything still compiles (in an appropriate singularity image), but it would be good if one / multiple of you could check if they get the same recognition results as before.

Backport AppTek changes to LM + LM lookahead code

---

src/Bliss/Lexicon.cc
src/Bliss/Lexicon.hh
src/Bliss/LexiconParser.cc
src/Bliss/LexiconParser.hh

Support for simple text lexica instead of XML-files.
This is meant for unconstrained search for which the XML-format is unnecessarily complicated.
Instead of an XML-lexicon, one can use a txt-file containing one label per line.
For example
```
A
B
C
```
will be parsed to a Bliss Lexicon equivalent to 
```
<?xml version="1.0" ?>
<lexicon>
<phoneme-inventory>
<phoneme>
<symbol>A</symbol>
<variation>none</variation>
</phoneme>
<phoneme>
<symbol>B</symbol>
<variation>none</variation>
</phoneme>
<phoneme>
<symbol>C</symbol>
<variation>none</variation>
</phoneme>
<phoneme>
</phoneme-inventory>
<lemma>
<orth>A</orth>
<phon>A</phon>
</lemma>
<lemma>
<orth>B</orth>
<phon>B</phon>
</lemma>
<lemma>
<orth>C</orth>
<phon>C</phon>
</lemma>
</lexicon>
```

Basic text lexicon parser

---

src/Onnx/Value.cc

The `set` function of `Onnx::Value` with a transposed FastMatrix is wrong. The assign logic is
```
for (u32 c = 0u; c < mat.nColumns(); c++) {
for (u32 r = 0u; r < mat.nRows(); r++) {
data[c * mat.nColumns() + r] = mat.at(r, c);
}
}
```
but it should be `data[c * mat.nRows() + r] = mat.at(r, c);`.
For example if `mat` is a FastMatrix of shape 1 x 3 then the current logic works like this:
1. `c = 0`, `r = 0`: `data[0] = mat.at(0, 0)`
2. `c = 1`, `r = 0`: `data[3] = mat.at(0, 1)`
3. `c = 2`, `r = 0`: `data[6] = mat.at(0, 2)`
With the fix it works properly like this:
1. `c = 0`, `r = 0`: `data[0] = mat.at(0, 0)`
2. `c = 1`, `r = 0`: `data[1] = mat.at(0, 1)`
3. `c = 2`, `r = 0`: `data[2] = mat.at(0, 2)`

Bugfix: ONNX value creation based on transposed FastMatrix

---

src/Core/CollapsedVector.hh

Vector that is automatically collapsed down to one element if all entries have the same value
From the outside it behaves like a normal vector. Whether it is collapsed or not only matters internally.
Example:
```
CollapsedVector<int> v;  // Internal data of v is [] with logical size 0
v.push_back(5);  // Normal push. Internal data of v is [5] with logical size 1
v.push_back(5);  // v stays collapsed. Internal data of v is [5] with logical size 2
std::cout << v.size() << std::endl;  // Prints "2"
std::cout << v[1] << std::endl;  // Prints "5"
v.push_back(6);  // v is expanded because the new value is different. Internal data of v is [5, 5, 6] with logical size 3
std::cout << v[2] << std::endl;  // Prints "6"
v.clear();  // Internal data of v is [] with logical size 0.
```

Add Core::CollapsedVector

---

src/Search/AdvancedTreeSearch/PersistentStateTree.cc
src/Search/AdvancedTreeSearch/PersistentStateTree.hh
src/Search/AdvancedTreeSearch/SearchSpace.cc
src/Search/AdvancedTreeSearch/SearchSpace.hh
src/Search/AdvancedTreeSearch/TreeBuilder.cc
src/Search/AdvancedTreeSearch/TreeBuilder.hh

Integrates the refactoring of the TreeBuilder from AppTek RASR. 
This mainly involves adjustments to allow different tree variants.
Code by @curufinwe

Refactor tree construction in AdvancedTreeSearch to allow multiple TreeBuilder types

---

src/Nn/LabelScorer/BufferedLabelScorer.cc
src/Nn/LabelScorer/BufferedLabelScorer.hh
src/Nn/LabelScorer/Makefile

Add `BufferedLabelScorer` class.
This is an extension of `LabelScorer` that implements some commonly used buffering logic for input features and timeframes as well as a flag that indicates whether more features are expected to be added to the buffer.
The class serves as a base class for other LabelScorers.

Add BufferedLabelScorer

---

src/Nn/LabelScorer/Encoder.cc
src/Nn/LabelScorer/Encoder.hh
src/Nn/LabelScorer/Makefile

Add `Encoder` class can take features (e.g. from feature flow) and run them through an encoder model to get encoder states. Works with input/output buffer logic, i.e. features get added to an input buffer and outputs are retrieved from an output buffer.
This will later get concrete implementations such as `OnnxEncoder` as subclasses and can be used to pre-process the input features of a LabelScorer in the context of encoder-decoder LabelScorers.

Add Encoder class for LabelScorers

---

src/Flow/InputNode.cc
src/Flow/InputNode.hh
src/Flow/Makefile
src/Flow/Module.cc
src/Flow/Network.hh
src/Flow/Types.hh

This is a pull request for the sake of adding the missing elements needed for testing the pybind11 implementation. The changes come from Apptek RASR given to me by my supervisors. Adds the InputNode class from streaming into Flow and some minor changes in other classes and modules.

Add Flow::InputNode to allow passing in samples without reading an audio file

---

src/Flf/IncrementalRecognizer.cc
src/Flf/Recognizer.cc
src/Flf/Traceback.cc
src/Search/AdvancedTreeSearch/AdvancedTreeSearch.cc
src/Search/AdvancedTreeSearch/SearchSpace.cc
src/Search/AdvancedTreeSearch/SearchSpace.hh
src/Search/AdvancedTreeSearch/SearchSpaceHelpers.hh
src/Search/AdvancedTreeSearch/Trace.cc
src/Search/AdvancedTreeSearch/Trace.hh
src/Search/Makefile
src/Search/Search.cc
src/Search/Search.hh
src/Search/SearchV2.hh
src/Search/Traceback.cc
src/Search/Traceback.hh
src/Search/Wfst/Traceback.cc
src/Search/Wfst/Traceback.hh
src/Speech/Recognizer.cc
src/Speech/Recognizer.hh

Abstract base class for search algorithms that can work in an online or offline manner.
In contrast to the previous `SearchAlgorithm` this receives features instead of `Mm::FeatureScorers` and the algorithm is supposed to perform scoring internally (usually with a `Nn::LabelScorer`).
The "workflow" usually happens as follows:
1. Check which `Speech::ModelCombination` (and possibly `Am::AcousticModel`) are needed by the search algorithm via `requiredModelCombination` (and `requiredAcousticModel`).
2. Create appropriate `Speech::ModelCombination` and provide it to the search algorithm via `setModelCombination`.
3. Signal segment start via `enterSegment`.
4. Pass audio features via `passFeature` or `passFeatures`.
5. Optionally call `decodeStep` or `decodeMore` to run the next search step(s) …

Add new `SearchAlgorithmV2` interface

---

src/Speech/AllophoneStateGraphBuilder.cc

When training CTC model with FSA created by AllophoneStateGraphBuilder, we observe around 5% relative WER degradation compared to training with built-in Pytorch CTC loss. We found out this is due to incorrect handling of repeated identical labels(e.g. aa in aachen when using character label unit). Without a forced blank in between, CTC topology can't differentiate loop and forward between repeated identical labels. After using the fixed version, we are able to get the same WER.

Fix CTCTopologyGraphBuilder: force blank label between two consecutive identical labels

---

src/Nn/LabelScorer/EncoderDecoderLabelScorer.cc
src/Nn/LabelScorer/EncoderDecoderLabelScorer.hh
src/Nn/LabelScorer/Makefile
src/Nn/Module.cc

Add a new LabelScorer class `EncoderDecoderLabelScorer`. This is a glue class to represent encoder-decoder model architectures. It consists of an encoder component that computes feature encodings without requiring a `ScoringContext` and a decoder component which is an arbitrary sub-LabelScorer that receives the encoded features as its inputs.
This class handles the information flow between its encoder and decoder components.

Add EncoderDecoderLabelScorer

---

src/Python/AllophoneStateFsaBuilder.cc
src/Python/AllophoneStateFsaBuilder.hh
src/Tools/LibRASR/PybindModule.cc

In training, it's sometimes beneficial to directly access the orthography instead of only seeing the FSA. E.g. in sequence concatenation, it's easy to concatenate strings and then build FSA than concatenating FSAs directly. This was implemented by Daniel and I just want to make the PR for him.

Add interface to librasr for direct access to orthography

---

src/Tools/Lm/Makefile

The Makefile of the `lm-util` tool was incorrect because the libraries are not in a group which can break when circular dependencies are present. This seemingly wasn't an issue before but breaks compilation now after the merge of #119. The wrap into `$(LD_START_GROUP) ... $(LD_END_GROUP)` is already present in the Makefiles of all other tools that use `LIBS_SEARCH` but was missing from `lm-util`.

Fix compilation of lm-utility tool

---

src/Search/LexiconfreeTimesyncBeamSearch/LexiconfreeTimesyncBeamSearch.cc
src/Search/LexiconfreeTimesyncBeamSearch/LexiconfreeTimesyncBeamSearch.hh
src/Search/TreeTimesyncBeamSearch/TreeTimesyncBeamSearch.cc
src/Search/TreeTimesyncBeamSearch/TreeTimesyncBeamSearch.hh

We revisited the new search algorithms again and came to the conclusion that it is mathematically more correct to perform the recombination of the hypotheses/extensions first and prune them afterwards. 
As a small optimization, we decided to score-prune first, then call the recombination function and finally apply beam-size-pruning. This approach remains mathematically valid, but a bit more efficient as we avoid many unnecessary `labelScorer_->extendedScoringContext` calls.
A small additional feature I added is the logging about statistics on the number of active trees.

Change order of pruning and recombination in the new search algorithms

---

src/Am/AdaptationTree.cc
src/Am/ClassicAcousticModel.cc
src/Am/ClassicAcousticModel.hh
src/Am/ClassicHmmTopologySet.hh
src/Am/Utilities.cc
src/Bliss/Lexicon.hh
src/Bliss/Phoneme.hh
src/Nn/BufferedAlignedFeatureProcessor.cc
src/Nn/PythonControl.cc
src/Nn/SegmentwiseNnTrainer.cc
src/Search/LinearSearch.cc
src/Search/StateTree.cc
src/Search/TreeBuilder.cc
src/Search/TreeTimesyncBeamSearch/TreeTimesyncBeamSearch.cc
src/Speech/AdvancedAccuracyFsaBuilder.cc
src/Speech/AlignmentWithLinearSegmentation.cc
src/Speech/AllophoneStateGraphBuilder.cc

Up to now, the acoustic model always required a special lemma silence to be present in the lexicon. As I found this annoying, I dug a bit deeper and changed several things to make silence optional.
This mainly involved introducing an invalid phoneme ID and an invalid lemma pronunciation, which can be returned instead of directly throwing an error. We can then check for an invalid ID/pronunciation only when silence is actually required.
I'm aware that these changes are somewhat inelegant in parts, but achieving good code style would likely require a major refactoring of the acoustic model implementation. I did my best to ensure I didn’t break anything, but I would be thankful if you could double-check.

Make special lemma "silence" optional in acoustic model

---

src/Search/TreeTimesyncBeamSearch/TreeTimesyncBeamSearch.cc

In the TreeTimesyncBeamSearch, we had a hardcoded check to force the LM to ignore the blank and silence lemma. There are however use cases where blank or silence are part of the LM as well. Therefore, we removed this hardcoded check and only check if the syntactic token sequence is not empty.
This also means that in the special lemmas blank and silence, the user needs to set `<synt/>` in the lexicon, otherwise the LM will score these lemmas. As this can easily happen by mistake, we added a warning for that.

Modify TreeTimesyncBeamSearch: don't force LM to ignore blank and silence
